#!/bin/bash

#David Parrott
#11239947
#CS 455 Homework 3 - Traffic Analysis


#2.1
#What is the average packet size, across all traffic in the trace?
#Describe how you computed this number
echo Question 2.1
cat flow.csv | cut -d "," -f6 | awk '{ total += $1; count++ } END { print "The average packet size is " total/count " bytes"}'
echo This was calculated by accumulating the total bytes on all packets and dividing it by the number of lines
echo 

#2.2
#Plot the Cumulative Probability Distribution


#2.3
echo Question 2.3
cat flow.csv | cut -d "," -f6 | awk '{ total += $1 } END { print "The total number of bytes across all ports is " total " bytes"}'

#need doctets (6) and port (16)
echo Calculating the top 10 port numbers by sender traffic volume
awk -F, 'NR > 1 {a[$16]+=$6}END{for(i in a)print i" "a[i]}' flow.csv | sort -k2 -nr | head -10 | column -t 

echo
echo Calculating the top 10 port numbers by receiver traffic volume
awk -F, 'NR > 1 {a[$17]+=$6}END{for(i in a)print i" "a[i]}' flow.csv | sort -k2 -nr | head -10 | column -t 

echo
echo A good example of why there are discrepancies between sent and received traffic
echo is port 80. This is the default port for HTTP traffic. A webserver will get 
echo many requests on this port. Port 443, used for HTTPS, will also get a lot of
echo requests. The size of a request and the size of a response can differ significantly.
echo

#2.4
#need doctets(6) srcaddr(11) and src_mask(21)
echo Question 2.4
echo Sorting IPs for analysis 
start="$(date +%s)"
awk -F, 'NR > 1 {a[$11"/"$21]+=$6}END{for(i in a)print i","a[i]}' flow.csv |\
awk -F, '{cmd = "ipcalc -n " $1; cmd | getline result; print result","$2;close(cmd)}' |\
awk -F, '{a[substr($1,9)]+=$2}END{j=1
	data_total=0
	command = "sort -nrk2 > sorted"
	for(i in a)
	{
		ind[j] = i
		j++
		data_total+=a[i]
		print i" "a[i] > "unsorted"
	} 
	command
	print "there are "j" prefixes and "data_total" bytes" 
	n=asort(ind)



	temp=0
	count=0
	for(i = 1; i < .001*j; i++)
	{
		temp+=a[ind[i]]
		count++
	}
	print "The top .1%("count") of prefixes account for "temp/data_total*10"% of the total data ("temp" bytes)" 
	temp=0
	count=0
	for(i = 1; i < .01*j; i++)
	{
		temp+=a[ind[i]]
		count++
	}
	print "The top 1%("count") of prefixes account for "temp/data_total*10"% of the total data ("temp" bytes)"
	temp=0
	count=0
	for(i = 1; i < .1*j; i++)
	{
		temp+=a[ind[i]]
		count++
	}
	print "The top 10%("count") of prefixes account for "temp/data_total*10"% of the total data ("temp" bytes)"


}' #| sort -k2 -nr | head -10 | column -t
end="$(date +%s)"
runtime=$((end-start))
echo IP sorting excuted in $runtime

echo Question 2.5
awk -F, 'NR > 1 {a[$11"/"$21]+=$6}END{WSU_BYTES=0
	WSU_COUNT=0
	total=0
	count=0
	for(i in a)
	{
		count++
		total+=a[i]
		if(i ~ /134.121/)
		{
			WSU_BYTES+=a[i]
			WSU_COUNT++
		}
	}
	print "WSU sent "(WSU_BYTES/total)*10"%("WSU_BYTES") of the total bytes and "WSU_COUNT/count"%("WSU_COUNT") of the total packets"
}' flow.csv 

awk -F, 'NR > 1 {a[$12"/"$22]+=$6}END{WSU_BYTES=0
	WSU_COUNT=0
	total=0
	count=0
	for(i in a)
	{
		count++
		total+=a[i]
		if(i ~ /134.121/)
		{
			WSU_BYTES+=a[i]
			WSU_COUNT++
		}
	}
	print "WSU received "(WSU_BYTES/total)*10"%("WSU_BYTES") of the total bytes and "WSU_COUNT/count"%("WSU_COUNT") of the total packets"
}' flow.csv 
#	total=0
#	for(i in a)
#	{
#		print i", "a[i]
#		count++
#		total+=a[i]
#	}

#	for(j=0;j<.001*count)
#	{

#	}
